version: "3.3"
services:
  web:
    build:
      context: ./webService
      dockerfile: Dockerfile
    ports:
      - "80:3000"
      - "443:3000"
    environment:
      - REDIS_HOST=redis
  redis:
    image: "redis:alpine"
